# Site settings
title: Alexandre VESSEREAU
subtitle: Homepage
tagline: Data Engineer, Scientist and Economist. 
#email: soumyadeep.das.m44@gmail.com
description: Data Engineer, Scientist and Economist. Passionate about anything really, as long as I keep learning new cool stuff! Currently building a mobile app! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://esquiroll.com" # the base hostname & protocol for your site
logo: assets/images/favicon.png
image: assets/images/og-pic.jpg


# Blog posts
words_per_minute : 160
future : true
read_more : "disabled"

# projects
collections:
    projects:
        output: true

myversion: 4.5.0

author:
    name: Alexandre VESSEREAU
    avatar : assets/images/profile_picture.png
    avatar-webp: assets/images/profile_picture.webp
    avatar-thumb: assets/images/profile_picture-thumb.jpg
    # author-bio : "Incoming PhD Student at ICRAR/UWA Perth."
    #author-bio : "Graduated with Dual Degree (B.Tech. and M.Tech.) in Engg. Physics, IIT Varanasi, India."
    #ads : https://ui.adsabs.harvard.edu/search/p_=0&q=orcid%3A0000-0002-3493-6638&sort=date%20desc%2C%20bibcode%20desc
    #facebook: https://www.facebook.com/TheSoumyadeepDas
    github: https://github.com/arkhemis
    #gitlab: https://gitlab.com/lordparthurnaax
    #googleplus: 
    #googlescholar : https://scholar.google.com/citations?user=02NSBH4AAAAJ&hl=en
    #instagram: https://www.instagram.com/lordparthurnaax/
    linkedin: https://www.linkedin.com/in/https://www.linkedin.com/in/alexandre-vessereau/
#orcid: https://orcid.org/0000-0002-3493-6638
    #pinterest:
    researchgate: https://www.researchgate.net/profile/Soumyadeep_Das9
    #slack:
    #stackoverflow : https://stackoverflow.com/users/4701760/lordparthurnaax
    #steam : https://steamcommunity.com/profiles/76561198859680680
    #twitter: https://twitter.com/lordparthurnaax



#social:
#  name: Alexandre VESSEREAU
#  links:
#    - https://twitter.com/lordparthurnaax
#    - https://www.instagram.com/lordparthurnaax/
#    - https://www.facebook.com/TheSoumyadeepDas
#    - https://github.com/lordparthurnaax
#    - https://gitlab.com/lordparthurnaax
#    - https://www.linkedin.com/in/soumyadeep01

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gzip
  - jekyll-brotli
  - jekyll-redirect-from

# Build settings
markdown: kramdown



exclude:
  - vendor  
